import os
import sys
import json
import asyncio

# Ensure parent directory is in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.base_agent import BaseAgent

class BusinessInsightsAgent(BaseAgent):
    """
    Business Insights Agent uses the Gemini API to analyze the scored leads dataset,
    identifies market trends, and produces a professional executive summary.
    """
    def __init__(self, mcp_manager=None, gemini_client=None):
        super().__init__("Business Insights Agent", mcp_manager, gemini_client)

    async def execute(self, task_input: dict) -> dict:
        """
        Generates business insights using the Gemini API.
        
        Args:
            task_input (dict): Context dictionary containing:
                - 'leads': list of scored leads
                - 'metrics': dict of aggregate metrics
                
        Returns:
            dict: Generated insights.
        """
        leads = task_input.get("leads", [])
        metrics = task_input.get("metrics", {})
        
        if not leads:
            self.logger.warning("No leads data passed to Business Insights Agent.")
            return {"success": False, "error": "No leads data available."}
            
        self.logger.info("Generating business insights using Gemini API...")
        
        # Format the top 5 high-value leads for context
        top_leads = sorted(leads, key=lambda x: x.get("score", 0), reverse=True)[:5]
        top_leads_str = ""
        for i, lead in enumerate(top_leads, 1):
            top_leads_str += (
                f"{i}. {lead['company_name']} ({lead['industry']}): Revenue: ${lead['annual_revenue']:,}, "
                f"Interactions: {lead['interactions_count']}, Conv. Rate: {lead['estimated_conversion_rate']}, "
                f"Score: {lead['score']} -> Tier: {lead['priority_tier']}\n"
            )
            
        # Formulate instructions prompt
        prompt = f"""
You are a senior business operations manager and business intelligence consultant.
Analyze the following lead data metrics and provide:
1. A brief executive summary of today's lead funnel.
2. Identified trends (e.g., high-value industry clusters, conversion patterns, lead source effectiveness).
3. Strategic recommendations for sales execution.

### Leads Funnel Metrics:
- Total Ingested Leads: {metrics.get('total_leads')}
- Hot Leads (Priority Score >= 70): {metrics.get('hot_leads')}
- Warm Leads (40 <= Score < 70): {metrics.get('warm_leads')}
- Cold Leads (Score < 40): {metrics.get('cold_leads')}
- Total Pipeline Revenue: ${metrics.get('total_revenue'):,.2f}
- Average Lead Score: {metrics.get('avg_score', 0):.1f}

### Top 5 Scored Leads (Priority):
{top_leads_str}

Please generate your response in professional, concise, business-ready markdown. Do not include markdown meta-blocks, just standard headings, bullet points, and paragraphs.
"""

        # Call Gemini if available, otherwise run fallback
        insights_text = ""
        if self.gemini_client:
            try:
                model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
                self.logger.info(f"Invoking Gemini model: {model_name}")
                
                response = self.gemini_client.models.generate_content(
                    model=model_name,
                    contents=prompt
                )
                
                insights_text = response.text
                self.logger.info("Insights successfully generated by Gemini API.")
            except Exception as e:
                self.logger.error(f"Gemini API invocation failed: {str(e)}. Falling back to rule-based insights.")
                insights_text = self._generate_fallback_insights(metrics, top_leads)
        else:
            self.logger.warning("Gemini Client not provided. Using rule-based fallback insights.")
            insights_text = self._generate_fallback_insights(metrics, top_leads)
            
        return {
            "success": True,
            "executive_summary": insights_text
        }
        
    def _generate_fallback_insights(self, metrics: dict, top_leads: list) -> str:
        """
        A rule-based fallback summary when the Gemini API is offline or not configured.
        """
        hot_pct = (metrics.get('hot_leads', 0) / metrics.get('total_leads', 1)) * 100
        top_leads_list = "".join([f"- **{l['company_name']}** ({l['industry']}) - Score: {l['score']} (Priority: {l['priority_tier']})\n" for l in top_leads])
        
        fallback = f"""### Executive Summary (System Generated Fallback)
Today's pipeline contains **{metrics.get('total_leads')} leads** representing a total estimated pipeline value of **${metrics.get('total_revenue'):,.2f}**. 
Of these, **{metrics.get('hot_leads')} leads ({hot_pct:.1f}%)** have been categorized as **High-Value (Hot)** due to substantial revenues and high engagement levels.

### Key Funnel Trends
* **High-Priority Leads**: The average lead score is **{metrics.get('avg_score', 0):.1f}**. The leads categorized as 'Hot' represent the highest likelihood of conversion and should be prioritized immediately.
* **Top Targets**:
{top_leads_list}

### Strategic Recommendations
1. **Immediate Outbound outreach**: Direct sales resources toward 'Hot' leads within 24 hours.
2. **Nurturing Campaigns**: Deploy marketing automations for 'Warm' leads to increase interactions.
3. **Data Review**: Filter out low-revenue 'Cold' leads to optimize CRM efficiency.
"""
        return fallback

if __name__ == "__main__":
    # Standard rule-based fallback test
    agent = BusinessInsightsAgent()
    result = asyncio.run(agent.execute({
        "leads": [
            {"company_name": "Test SaaS", "industry": "SaaS", "annual_revenue": 12000000, "interactions_count": 8, "estimated_conversion_rate": 0.75, "score": 84, "priority_tier": "Hot"}
        ],
        "metrics": {"total_leads": 1, "hot_leads": 1, "total_revenue": 12000000, "avg_score": 84}
    }))
    print(result["executive_summary"])
