import os
import sys
import json
import asyncio

# Ensure parent directory is in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.base_agent import BaseAgent

class ReportGenerationAgent(BaseAgent):
    """
    Report Generation Agent interacts with the Reporting MCP Server to generate Plotly charts
    and compile a beautifully styled HTML/Markdown executive report.
    """
    def __init__(self, mcp_manager=None, gemini_client=None):
        super().__init__("Report Generation Agent", mcp_manager, gemini_client)

    async def execute(self, task_input: dict) -> dict:
        """
        Executes the reporting tools to generate files.
        
        Args:
            task_input (dict): Context dictionary containing:
                - 'leads': list of scored leads
                - 'metrics': dict of aggregate metrics
                - 'executive_summary': markdown generated by Business Insights Agent
                - 'tasks': generated follow-up tasks (optional, default empty list)
                
        Returns:
            dict: Paths to the generated HTML and Markdown reports.
        """
        leads = task_input.get("leads", [])
        metrics = task_input.get("metrics", {})
        executive_summary = task_input.get("executive_summary", "")
        tasks = task_input.get("tasks", [])
        
        self.logger.info("Initializing report compiler...")
        
        # 1. Generate Plotly charts using Reporting Server
        leads_json = json.dumps(leads)
        charts_response = await self.call_mcp_tool(
            "Reporting Server",
            "generate_plotly_charts",
            {"leads_json": leads_json}
        )
        
        if isinstance(charts_response, str):
            charts_data = json.loads(charts_response)
        else:
            charts_data = charts_response
            
        charts = charts_data.get("charts", {}) if charts_data.get("success", False) else {}
        
        # 2. Compile styled HTML report using Reporting Server
        metrics_json = json.dumps(metrics)
        tasks_json = json.dumps(tasks)
        
        html_report_content = await self.call_mcp_tool(
            "Reporting Server",
            "compile_html_report",
            {
                "executive_summary": executive_summary,
                "metrics_json": metrics_json,
                "leads_json": leads_json,
                "tasks_json": tasks_json
            }
        )
        
        # Write reports to logs/data directories
        reports_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "logs"
        )
        os.makedirs(reports_dir, exist_ok=True)
        
        html_path = os.path.join(reports_dir, "executive_report.html")
        md_path = os.path.join(reports_dir, "executive_report.md")
        
        # Write HTML Report
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_report_content)
            
        # Write Markdown Report (for clean plain view)
        md_content = f"""# BusinessPilot AI Executive Report
Generated automatically by BusinessPilot Orchestrator.

## Funnel Summary
- Total leads: {metrics.get('total_leads')}
- Hot leads: {metrics.get('hot_leads')}
- Warm leads: {metrics.get('warm_leads')}
- Cold leads: {metrics.get('cold_leads')}
- Pipeline value: ${metrics.get('total_revenue'):,.2f}

## Insights & Trends
{executive_summary}

## Follow-up Action Items
"""
        for t in tasks:
            md_content += f"- **[{t.get('priority', 'MEDIUM').upper()}]** {t.get('lead_company', 'General')}: {t.get('task_description')} (Assignee: {t.get('assignee')})\n"
            
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)
            
        self.logger.info(f"Reports compiled: HTML -> {html_path}, MD -> {md_path}")
        
        return {
            "success": True,
            "html_report_path": html_path,
            "md_report_path": md_path,
            "html_content": html_report_content,
            "md_content": md_content,
            "charts": charts
        }

if __name__ == "__main__":
    agent = ReportGenerationAgent()
    result = asyncio.run(agent.execute({
        "leads": [{"company_name": "Test SaaS", "score": 84, "priority_tier": "Hot", "annual_revenue": 10000000}],
        "metrics": {"total_leads": 1, "hot_leads": 1, "total_revenue": 10000000, "avg_score": 84},
        "executive_summary": "Test Summary text.",
        "tasks": [{"lead_company": "Test SaaS", "task_description": "Follow up", "assignee": "John", "priority": "High"}]
    }))
    print("HTML path generated:", result["html_report_path"])
